# action.yml
name: 'ImageMagick-pdf'
description: 'Use ImageMagick in your repo as in your desktop'
branding:
  icon: 'upload'  
  color: 'yellow'
inputs:
  command:
    description: 'ImageMagick command to be executed'
    required: true
    default: 'mogrify -path src/assets/images -auto-orient -resize x500 src/assets/images/*.*'
outputs:
  time:
    description: 'The time we greeted you'
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
